#!/bin/bash
#
# bash completion, based on docker/contrib/completion/bash/docker

# TODO: This is set in python code also
export FACET_DIRECTORY=~/.facet

__facet_previous_extglob_setting=$(shopt -p extglob)
shopt -s extglob

__facet_complete_commands() {
    COMPREPLY=( $(compgen -W "${commands[*]}" -- "$cur") )
}

__facet_complete_facets() {
    local facets=$(ls $FACET_DIRECTORY/facets | tr '\n' ' ')
    COMPREPLY=( $(compgen -W "$facets" -- "$cur") )
}

_facet_bump() {
    __facet_complete_facets
}

_facet_cd() {
    __facet_complete_facets
}

_facet_config() {
    __facet_complete_facets
}

_facet_directory() {
    __facet_complete_facets
}

_facet_doing() {
    __facet_complete_facets
}

_facet_done() {
    __facet_complete_facets
}

_facet_notes() {
    __facet_complete_facets
}

_facet_pr() {
    __facet_complete_facets
}

_facet_edit() {
    __facet_complete_facets
}

_facet_facet() {
    __facet_complete_commands
}

_facet_fetch() {
    __facet_complete_facets
}

_facet_follow() {
    __facet_complete_facets
}

_facet_migrate() {
    __facet_complete_facets
}

_facet_github() {
    __facet_complete_facets
}

_facet_jira() {
    __facet_complete_facets
}

_facet_rm() {
    __facet_complete_facets
}

_facet_show() {
    __facet_complete_facets
}

_facet_todo() {
    __facet_complete_facets
}

_facet_workon() {
    __facet_complete_facets
}

_facet() {
    local previous_extglob_setting=$(shopt -p extglob)
    shopt -s extglob

    local commands=(
        bump
        cd
        config
        create
        current
        directory
        doing
        done
        edit
        fetch
        follow
        github
        jira
        ls
        migrate
        notes
        pr
        rm
        show
        todo
        workon
    )

    COMPREPLY=()
    local cur prev words cword
    _get_comp_words_by_ref -n : cur prev words cword

    local command='facet' command_pos=0
    local counter=1
    while [ $counter -lt $cword ]; do
      case "${words[$counter]}" in
          *)
              command="${words[$counter]}"
              command_pos=$counter
              break
              ;;
      esac
      (( counter++ ))
    done

    local completions_func=_facet_${command}

    declare -F $completions_func >/dev/null && $completions_func

    eval "$previous_extglob_setting"
    return 0
}

eval "$__facet_previous_extglob_setting"
unset __facet_previous_extglob_setting

complete -F _facet facet
complete -F _facet f
